trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '91c7cb24-569e-4d44-8a45-f9703159ec96'

  # Web app name
  webAppName: 'diceatthetable'
  
  # Environment name
  environmentName: 'diceatthetable'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildFrontend
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Npm@1
      displayName: "Install dependencies"
      inputs:
        command: 'install'
        workingDir: 'frontend'
    - task: Npm@1
      displayName: "Create artifact"
      inputs:
        command: 'custom'
        customCommand: 'run build --if-present'
        workingDir: 'frontend'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/frontend/build'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/frontend-$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/frontend-$(Build.BuildId).zip
      artifact: frontend

- stage: BuildBackend
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      displayName: 'Use Node version'
      inputs:
        versionSpec: 10.x

    - task: Npm@0
      displayName: 'npm install'
      inputs:
        cwd: backend
        arguments: '--force'

    - task: ArchiveFiles@2
      displayName: 'Archive files '
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/backend'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/backend-$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/backend-$(Build.BuildId).zip
      artifact: backend



# - stage: Deploy
#   displayName: Deploy stage
#   dependsOn: Build
#   condition: succeeded()
#   jobs:
#   - deployment: Deploy
#     displayName: Deploy
#     environment: $(environmentName)
#     pool: 
#       vmImage: $(vmImageName)
#     strategy:
#       runOnce:
#         deploy:
#           steps:            
#           - task: AzureRmWebAppDeployment@4
#             displayName: 'Azure App Service Deploy: diceatthetable'
#             inputs:
#               azureSubscription: $(azureSubscription)
#               appType: webAppLinux
#               WebAppName: $(webAppName)
#               packageForLinux: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
#               RuntimeStack: 'NODE|10.10'
#               StartupCommand: 'npm run start'
#               ScriptType: 'Inline Script'
#               InlineScript: |
#                 npm install
#                 npm run build --if-present