trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '91c7cb24-569e-4d44-8a45-f9703159ec96'
  azureStorageSubscription: 'Jason Personal AIRs Subscription (04fe963c-dced-4688-9372-1be7f86c986f)'

  # Web app name
  webAppName: 'diceatthetable'
  
  # Environment name
  environmentName: 'diceatthetable'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildFrontend
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build Frontend
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        repository: frontend
        command: build
        Dockerfile: frontend/Dockerfile

    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: 'acr'
        repository: frontend
        command: push
        tags: |
          latest
          v1.$(Build.BuildId)

- stage: BuildBackend
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build Backend
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        repository: backend
        command: build
        Dockerfile: backend/Dockerfile

    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: 'acr'
        repository: backend
        command: push
        tags: |
          latest
          v1.$(Build.BuildId)
