name = "dicewizard-net"
main = "dist/index.mjs"

compatibility_date = "2022-05-28"
compatibility_flags = []

[durable_objects]
bindings = [
  { name = "TABLE", class_name = "Table" }
]

[[migrations]]
tag = "v1"
new_classes = ["Table"]

[build]
command = "node build.js"

[vars]
FRONTEND_URI = "https://dicewizard.net"
